server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bigdata?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
mybatis:
  type-aliases-package: com.zhj.entity
  mapper-locations: classpath:mapper/*Mapper.xml

data:
  config:
    cn:
      usrname: 123456
      password: 456789